# Very Good Analysis (https://pub.dev/packages/very_good_analysis)
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/.pub-cache/**"
    - "**/build/**"
    - '**/**.codegen.g.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    use_setters_to_change_properties: false
    one_member_abstracts: false
    public_member_api_docs: false
    cascade_invocations: false
